### PR TITLE
Dark Mode Button

### PR DESCRIPTION
**Pull request by Anupamgupt**
Added Button with some functionality
Screenshot (50)
Screenshot (51)

### CODE REVIEW

**Review by VG-1 — APPROVED** [review]
Thanks for adding the feature @Anupamgupt :)

**Comment by VG-1** [comment]
@Anupamgupt actually this merge has affected the code badly.
Like the css of the card is being affected.
Would you like to work on it by creating another pr and issue?
Pr should I revert this pr?

**Comment by Anupamgupt** [comment]
Sure, I can work on it again

**Comment by VG-1** [comment]
sure please do work on it.
raise an issue for it.

**Pull request merged**
