### PR TITLE
fixed the css

### PR DESCRIPTION
**Pull request by Anupamgupt**

### CODE REVIEW

**Review by VG-1 — COMMENTED** [review]
hey @Anupamgupt can you send the gif or video of your code working.
I will prefer video.

**Comment by Anupamgupt** [comment]
> hey @Anupamgupt can you send the gif or video of your code working. I will prefer video.

Sure will be sending soon

**Comment by VG-1** [comment]
ohk

**Comment by Anupamgupt** [comment]
> ohk

Visit my Drive link to see the video https://drive.google.com/file/d/1MvjjPAFNYF36ucIg_RpD33hXCWxiUFLT/view?usp=sharing

**Comment by VG-1** [comment]
Thank you so much @Anupamgupt 
I really appreciate your work.
Merging your PR.
Stay connected :)

**Comment by Anupamgupt** [comment]
I think you have merged conflicts and therefore the main branch again require some changes, I can again fix it for you  :)

**Comment by Anupamgupt** [comment]
> Thank you so much @Anupamgupt I really appreciate your work. Merging your PR. Stay connected :)

Sure

**Pull request merged**
